import HautevilleHouse.BranchingProcessesGaltonWatsonBirthFoundationCanonicalLaneLean.AdmissibleClass
import HautevilleHouse.BranchingProcessesGaltonWatsonBirthFoundationCanonicalLaneLean.BridgeLemmas
import HautevilleHouse.BranchingProcessesGaltonWatsonBirthFoundationCanonicalLaneLean.GateLemmas
import HautevilleHouse.BranchingProcessesGaltonWatsonBirthFoundationCanonicalLaneLean.FinalTheorem
import HautevilleHouse.BranchingProcessesGaltonWatsonBirthFoundationCanonicalLaneLean.ExtinctionCriteria
import HautevilleHouse.BranchingProcessesGaltonWatsonBirthFoundationCanonicalLaneLean.GeneratingFunctions

namespace HautevilleHouse
namespace BranchingProcessesGaltonWatsonBirthFoundationCanonicalLaneLean

-- This module aggregates all imports for the package.

theorem package_closed (A : AdmissibleClass) : ConstrainedGaltonWatsonClosure A :=
  constrained_galton_watson_endgame A

end BranchingProcessesGaltonWatsonBirthFoundationCanonicalLaneLean
end HautevilleHouse